# Generated by Django 3.2.4 on 2023-02-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_pk',
        ),
    ]
