# Generated by Django 3.2.4 on 2023-02-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230221_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phonenum',
        ),
    ]
