# Generated by Django 3.2.4 on 2023-02-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
    ]
