# Generated by Django 3.2.4 on 2023-02-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20230223_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='userImage',
        ),
    ]
