# Generated by Django 3.2.4 on 2023-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_card_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImage'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagcontent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
