# Generated by Django 4.1.7 on 2023-02-23 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0004_card_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='friends',
        ),
        migrations.AddField(
            model_name='card',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
